package httpapi

import (
	"context"
	"errors"
)

// Authenticator gates LAN-facing endpoints on the admin-password Bearer token.
type Authenticator interface {
	// Authorize reports whether the presented secret (Bearer token) is valid.
	Authorize(secret string) bool
}

// StatusProvider exposes a read-only snapshot of buddy state.
type StatusProvider interface {
	Status() Status
}

// Status is a transport-agnostic snapshot of the device's buddy state.
type Status struct {
	State           string
	Connected       bool
	SessionsRunning int
	TokensToday     int
	HasPending      bool
	PendingID       string
	PendingTool     string
	PendingHint     string
}

// ApprovalService relays a Desktop approval decision over BLE and updates counters.
type ApprovalService interface {
	Approve(id string) error
	Deny(id string) error
}

// Sentinel errors the approval handler maps to HTTP 409 Conflict.
var (
	ErrNoPending      = errors.New("no pending prompt")
	ErrPromptMismatch = errors.New("prompt id mismatch")
)

// CodeApprovalRequest is a Claude Code permission prompt forwarded by the plugin hook.
type CodeApprovalRequest struct {
	ID    string         // correlation id, generated by the hook
	Tool  string         // e.g. "Bash", "Edit", "mcp__server__tool"
	Hint  string         // short human string for TTS/LED (derived if empty)
	Input map[string]any // raw tool_input, for richer device rendering
}

// CodeApprovalService blocks Request until the on-device agent approves/denies or it times out.
type CodeApprovalService interface {
	// Request registers a pending approval, triggers the device cue, and blocks
	// until resolved or timed out. Returns "allow", "deny", or "timeout".
	Request(ctx context.Context, req CodeApprovalRequest) (string, error)
	// Approve / Deny resolve a pending request by id. ErrNoPending if the id is
	// unknown or already resolved.
	Approve(id string) error
	Deny(id string) error
	// Pending lists the currently-blocked requests (for /status visibility).
	Pending() []CodeApprovalRequest
}

// ActivitySink receives Claude Code activity pushed by the plugin.
type ActivitySink interface {
	Notify(level, title, subtitle string, sound bool)
	Usage(fiveHour, sevenDay int, reset5h, reset7d string, sound bool)
}
